spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.100.129:3306/star_graph?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 87sdhf298TYUUIz2!
  data:
    redis:
      host: 192.168.100.129
      port: 6379
  freemarker:
    template-loader-path: classpath:/templates/
    suffix: .ftl
    charset: UTF-8

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      table-prefix: sg_

logging:
  level:
    root: info

star-graph:
  comfyui:
    base-url-and-port: http://192.168.3.26:8188
    connection-timeout-seconds: 3
    read-timeout-seconds: 10
    retry-on-connection-failure: true
    connection-pool:
      keep-alive-duration: 5
  ollama:
    connection:
      base-url: http://192.168.3.26:11434
      connect-timeout: 5
      read-timeout: 120
    model: qwen3:8b

